### ISSUE TITLE
install.inf separator 2nd hidden

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/syn_find_in_files#2]
To show separator2, write capt "-2", for separ3 write "-3"
Now it's SW problem with separators

**Comment by kvichans** [comment]
Что такое "separator2"?

**Comment by Alexey-T** [comment]
второй сепапатор в одном меню. Он имеет caption =-

**Comment by kvichans** [comment]
Вот так правильно?:
```
[ini10]
section=Commands
id=&Find in Files\-
params=_

[ini30]
section=Commands
id=&Find in Files\-2
params=_
```

**Comment by Alexey-T** [comment]
да, это как фикс.
